Opportunity Lifecyle: {
  grid-columns: 3
  grid-gap: 20

  hubspot: {
    label: Hubspot
    opp1 -> t
    t -> _.jira.sln
    t -- slnp: {
      style.stroke: transparent
    }
    t: {
      label: Ticket created
      shape: sql_table
      S1
      S2
    }
    opp1: {
      label: Opp1 created
      shape: sql_table
      S1: scope item 1
      S2: scope item 2
    }
    slnp: {
      label: Proposal created
      shape: sql_table
      S1
      S2
    }
    slnpa: {
      label: Proposal accepted
      shape: sql_table
      S1
    }
    slnsow: {
      label: SOW signed
      shape: sql_table
      S1
    }
    slncr: {
      label: CR form signed
      shape: sql_table
      CR1
    }
    opp2: {
      label: CR Opp2
      shape: sql_table
      CR1
    }
    slncr -> opp2
    # slnp -- slnsow: {
    #   style.stroke: transparent
    # }
    slnp -> slnpa -> slnsow
    slnsow -- slncr: {
      style.stroke: transparent
    }
  }
  sheets: {
    label: Pipeline

    # opp-estimate -- _.jira.sln
    opp-estimate: {
      label: P&L
    }
  }
  finance: {
    label: Finance
    # placeholder: {
    #   style.opacity: 0.1
    # }
    # placeholder -- opps
    _.hubspot.opp1 -- opps: {
      style.stroke-dash: 5
      style.opacity: .2
    }
    _.hubspot.opp2 -- opps: {
      style.stroke-dash: 5
      style.opacity: .2
    }
    opps: {
      label: Revenue
      shape: sql_table
      opp1: PS Days, PS Sales price
      opp2: PS Days, PS Sales price
    }
    cost: {
      label: Cost incurred
      shape: sql_table
      PS1: Budget, Actual
      PSCR1: Budget, Actual
    }
    opps -- cost: {
      style.opacity: 0
    }
    _.harvest.pcode1 -- cost: {
      style.stroke-dash: 5
      style.opacity: .2
    }
    _.harvest.pcode2 -- cost: {
      style.stroke-dash: 5
      style.opacity: .2
    }
    # placeholder -- revenue
  }
  jira: {
    label: SLN / Project Jira
    height: 100
    sln: {
      label: SLN created
      shape: sql_table
      S1
      S2
    }
    slne: {
      label: SLN estimated
      shape: sql_table
      S1
      S2
    }
    ptkt: {
      label: "Project"
      shape: sql_table
      S1
    }

    newcr: {
      label: "Project: CR Identified"
      shape: sql_table
      CR1: Approved by client
    }

    ptkt -> newcr
    sln -> slne
    slne -> _.hubspot.slnp

    _.hubspot.slnsow -> ptkt
    newcr -> _.hubspot.slncr
  }

  harvest: {
    label: Harvest

    pcode1: {
      label: Project Code - PS1
      shape: sql_table
      budgeted-days
      actual-days
      quoted-amount
    }
    pcode2: {
      label: Project Code - PSCR1
      shape: sql_table
      budgeted-days
      actual-days
      quoted-amount
    }
    pcode1 -- pcode2: {
      style.opacity: 0
    }

    pcode1 -- work1: {
      style.stroke-dash: 5
      style.opacity: 0
    }
    pcode2 -- work1: {
      style.stroke-dash: 5
      style.opacity: 0
    }

    work1: {
      label: Time tracking
      shape: sql_table
      style.opacity: 0.3
      budgeted-days: Effort in Days incl. contingency
      actual-days: Effort actually spent across roles
      quoted-amount: Price quoted to client in client currency
      height: 200
    }

    _.jira.ptkt -- pcode1: {
      style.stroke-dash: 5
      style.opacity: .2
    }
    _.jira.newcr -- pcode2: {
      style.stroke-dash: 5
      style.opacity: .2
    }
  }
}
